refactor+test

diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -1,6 +1,40 @@
-#!/bin/bash 
+#!/bin/bash
 
-bin/build "test_`date +"%s"`"
+DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
 
-docker run --rm -v "`pwd`:/server" monitor bin/docker/test.sh
+. "${DIR}/bash/vars"
 
+build_name="test_`date +"%s"`"
+
+echo "Building docker image..."
+bin/docker/build $build_name > /dev/null
+
+if ! [ $? -eq 0 ];
+then
+    echo "Building failed!"
+    exit 1
+fi
+
+debug="test=1"
+if [ "${1}" = "dbg" ];
+then
+    debug="SERVER_DEBUG=1"
+fi
+
+image_name="${IMAGE_NAME}:${VERSION}"
+
+echo "Testing code: "
+docker run --rm \
+    -v "`pwd`:/server" \
+    -e "${debug}" \
+    --name $build_name \
+    --hostname $build_name \
+    $image_name \
+    bin/docker/test.sh
+
+if [ $? -eq 0 ];
+then
+    echo "TEST_OK";
+else
+    echo "TEST_FAIL";
+fi
